### ISSUE TITLE
BUG-taipy create fails if the project folder already exists

### ISSUE THREAD

**Issue by anunayasri** [Avaiga/taipy#1202]
**Description**
`taipy create` command fails if the project folder already exists.

**How to reproduce**

```sh
taipy create 
# accept defaults. Default root folder name is 'taipy_application'

# Run the create again and accept defaults
taipy create
```

Fails with error -

```sh
❯ taipy create --template=scenario-management
Application root folder name [taipy_application]:
Application main Python file [main.py]:
Application title [Taipy Application]:
Does the application use TOML Config? [No]:
Traceback (most recent call last):
  File "/Users/anunayasri/workspace/taipy/./extaipy.py", line 8, in <module>
    sys.exit(_entrypoint())
             ^^^^^^^^^^^^^
  File "/Users/anunayasri/workspace/taipy/taipy/_entrypoint.py", line 62, in _entrypoint
    _ScaffoldCLI.handle_command()
  File "/Users/anunayasri/workspace/taipy/taipy/_cli/_scaffold_cli.py", line 49, in handle_command
    cookiecutter(cls._TEMPLATE_MAP[args.template])
  File "/Users/anunayasri/workspace/taipy/.venv/lib/python3.11/site-packages/cookiecutter/main.py", line 114, in cookiecutter
    result = generate_files(
             ^^^^^^^^^^^^^^^
  File "/Users/anunayasri/workspace/taipy/.venv/lib/python3.11/site-packages/cookiecutter/generate.py", line 291, in generate_files
    project_dir, output_directory_created = render_and_create_dir(
                                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anunayasri/workspace/taipy/.venv/lib/python3.11/site-packages/cookiecutter/generate.py", line 223, in render_and_create_dir
    raise OutputDirExistsException(msg)
cookiecutter.exceptions.OutputDirExistsException: Error: "taipy_application" directory already exists


**Expected behavior**
 It should exit gracefully, after declaring that the folder already exists. Or it can ask for a different folder name if the folder already exists.


**Runtime environment**
Please specify relevant indications.
 - Taipy version (or branch name): `develop`
 - OS: Mac OS

**Comment by jrobinAV** [comment]
Thank you for reporting the issue. Indeed, it should at least exit gracefully with a good error message.
