### ISSUE TITLE
[🐛 BUG] When updating app with state function, it does not return dict from user-defined function

### ISSUE THREAD

**Issue by kurvaraviteja355** [Avaiga/taipy#1539]
### What went wrong? 🤔

I have some user-defined functions that pull data from the API. The API has parameters and it returns dict or list.
From the app when i try to update the api parameters, the state object is not return the dict 

The code used to update:

```python
def update_budget_data(state):
          total_budget = state.total_budget
         minimum_budget = state.minimum_budget
         channel_1 = state.channel_1
         channel_2 = state.channel_2
         notify(state,  'Optimizing the Budget...')
        state.inputdata = get_budget_data(float(total_budget), float(minimum_budget), float(channel_1), float(channel_2))
        print('Updating initial Budget `data.......')
```

inputdata returns as  `<taipy.gui.utils._map_dict._MapDict object at 0x000002B59F30AF50>`

How can i get my original dict? 

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
@kurvaraviteja355  `<_MapDict>._dict` should return you the original dict. So, `your_dict_variable._dict`

Should something be done so the developer can have the dict directly and not the _MapDict in its callback? @FredLL-Avaiga @FabienLelaquais

**Comment by FredLL-Avaiga** [comment]
I suppose we could look into it, yes

**Comment by kurvaraviteja355** [comment]
`<_MapDict>._dict` should return you the original dict. So, `your_dict_variable._dict`

Thank you its working

**Comment by FlorianJacta** [comment]
This code is breaking because the dict is not the original dict (a user experienced this issue):

## Code

```python
from taipy.gui import Gui
import taipy.gui.builder as tgb
import numpy as np

master_data = {
    0: {
        "source": "td",
        "name": "SineWave_1Hz",
        "symbol": "SIN1",
        "timeframe": "minute",
        "start_date": "2024-01-01",
        "end_date": "2024-01-05",
        "calc": "linear",
        "returns": False,
        "composite": False,
        "interpolation": "linear",
        "data": np.sin(2 * np.pi * 1 * np.linspace(0, 1, 500)),
    }
}


def change_data(s, i, p):
    master_data = s.master_data # master_data = s.master_data._dict # with this expression, the code is working
    master_data[0]["data"] = np.sin(
        2 * np.pi * 1.5 * np.linspace(0, 1, 500) + np.pi / 4
    )
    s.master_data = master_data


with tgb.Page() as page:
    tgb.button("change_data", on_action=change_data)
    tgb.text(lambda master_data: str(master_data[0]["data"]))


Gui(page).run(debug=True)
```


## Error
```
C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\gui.py:1539: TaipyGuiWarning: on_action(): Exception raised in 'change_data()':
Traceback (most recent call last):
  File "C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\gui.py", line 1535, in __call_function_with_args
    action_function(*args)
  File "c:\Users\jacta\OneDrive\Bureau\taipy\Code\demo-sap\t.py", line 24, in change_data
    master_data[0]["data"] = np.sin(
    ~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\utils\_map_dict.py", line 47, in __setitem__
    self._update_var(key, value)
  File "C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\utils\_map_dict.py", line 40, in <lambda>
    return _MapDict(value, lambda s, v: self._update_var(f"{key}.{s}", v))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\utils\_bindings.py", line 51, in <lambda>
    return _MapDict(value._dict, lambda k, v: ud.__gui._update_var(f"{name}.{k}", v))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\gui.py", line 763, in _update_var     
    _setscopeattr_drill(self, hash_expr, value)
  File "C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\utils\_attributes.py", line 42, in _setscopeattr_drill
    _attrsetter(gui._get_data_scope(), name, value)
  File "C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\utils\_attributes.py", line 57, in _attrsetter
    obj = getattr(obj, sub_name)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\utils\_map_dict.py", line 68, in __getattr__
    value = self._dict.__getitem__(attr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '0'

  _warn(f"on_action(): Exception raised in '{action_function.__name__}()'", e)
C:\Users\jacta\.conda\envs\patch\Lib\site-packages\taipy\gui\gui.py:1511: TaipyGuiWarning: on_action(): 'change_data' is not a valid function.
  _warn(f"on_action(): '{action}' is not a valid function.")

```

**Comment by FlorianJacta** [comment]
Another user experienced the issue. I put a `._dict` inside the viz elements to make it work. There was no errors, it was showing on the page that the object was of type Mapdict.

```python
from taipy.gui import Gui, State, notify, navigate
import taipy.gui.builder as tgb

results_ready = False
nav_parameters = {}


def on_navigate(state: State, page_name: str, parameters: dict) -> str:
    print("on_navigate called...")
    print(page_name, parameters)
    state.nav_parameters = parameters
    return page_name


with tgb.Page() as root_page:
    tgb.text("# Results Page", mode="md")
    tgb.text("Navigation Parameters:", mode="md")
    tgb.text("*{nav_parameters._dict}*", mode="md")

pages = {"/": root_page, "results": "Page results"}

# http://localhost:5000/results?id=Florian&age=32
Gui(pages=pages).run()

```

**Comment by FlorianJacta** [comment]
I had this issue again when prototyping a demo. An object was not initialized properly using a `'taipy.gui.utils._map_dict._MapDict'`:
```
on_level_change(): callback function raised an exception:

    Invalid value of type 'taipy.gui.utils._map_dict._MapDict' received for the 'center' property of layout.mapbox
        Received value: <taipy.gui.utils._map_dict._MapDict object at 0x0000021641B4B5D0>

    The 'center' property is an instance of Center
    that may be specified as:
      - An instance of :class:`plotly.graph_objs.layout.mapbox.Center`
      - A dict of string/value properties that will be passed
        to the Center constructor

        Supported dict properties:

            lat
                Sets the latitude of the center of the map (in
                degrees North).
            lon
                Sets the longitude of the center of the map (in
                degrees East).
```
