### ISSUE TITLE
[🐛 BUG] Can't install taipy develop

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy#1754]
### What went wrong? 🤔

I can't install taipy develop using
```bash
pip install git+https://github.com/Avaiga/taipy.git
```

It fails with stacktrace:
```bash
Building wheels for collected packages: taipy
  Building wheel for taipy (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for taipy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [109 lines of output]
      running bdist_wheel
      running build
      running build_py

      added 6 packages, and audited 8 packages in 697ms

      found 0 vulnerabilities
      npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
      npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
      npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
      npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
      npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
      npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
      npm WARN deprecated domexception@4.0.0: Use your platform's native DOMException instead
      npm WARN deprecated mumath@3.3.4: Redundant dependency in your project.

      added 1404 packages, and audited 1405 packages in 30s

      285 packages are looking for funding
        run `npm fund` for details

      found 0 vulnerabilities

      > taipy-gui@4.0.0 build
      > webpack --mode production


      <--- Last few GCs --->

      [20064:0000018241F39350]    49674 ms: Scavenge 2022.6 (2069.6) -> 2022.0 (2079.8) MB, 4.87 / 0.00 ms  (average mu = 0.662, current mu = 0.349) allocation failure;
      [20064:0000018241F39350]    49702 ms: Scavenge 2028.7 (2079.8) -> 2026.7 (2080.3) MB, 11.51 / 0.00 ms  (average mu = 0.662, current mu = 0.349) allocation failure;
      [20064:0000018241F39350]    50152 ms: Scavenge 2029.8 (2080.3) -> 2028.4 (2100.6) MB, 440.49 / 0.00 ms  (average mu = 0.662, current mu = 0.349) allocation failure;


      <--- JS stacktrace --->

      FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
       1: 00007FF7123C433F node::SetCppgcReference+15695
       2: 00007FF71233EC26 EVP_MD_meth_get_input_blocksize+78566
       3: 00007FF712340A11 EVP_MD_meth_get_input_blocksize+86225
       4: 00007FF712DAA7E1 v8::Isolate::ReportExternalAllocationLimitReached+65
       5: 00007FF712D93F78 v8::Function::Experimental_IsNopFunction+1336
       6: 00007FF712BF57E0 v8::Platform::SystemClockTimeMillis+659552
       7: 00007FF712BF2868 v8::Platform::SystemClockTimeMillis+647400
       8: 00007FF712C07B7A v8::Platform::SystemClockTimeMillis+734202
       9: 00007FF712C083F7 v8::Platform::SystemClockTimeMillis+736375
      10: 00007FF712C16D1F v8::Platform::SystemClockTimeMillis+796063
      11: 00007FF7128D72E5 v8::CodeEvent::GetFunctionName+116773
      12: 00007FF6B2E1AAFA
      Building taipy-gui frontend bundle in C:\Users\asaju\AppData\Local\Temp\pip-req-build-fcfk88v3.
      Traceback (most recent call last):
        File "C:\Users\asaju\AppData\Local\Temp\pip-req-build-fcfk88v3\tools\frontend\bundle_build.py", line 56, in <module>
          build_gui(root_path)
        File "C:\Users\asaju\AppData\Local\Temp\pip-req-build-fcfk88v3\tools\frontend\bundle_build.py", line 30, in build_gui
          subprocess.run(["npm", "run", "build"], cwd=root_path / "frontend" / "taipy-gui", check=True, shell=with_shell)
        File "C:\Python311\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 134.       
      Traceback (most recent call last):
        File "C:\Users\asaju\Desktop\develop_test\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\asaju\Desktop\develop_test\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\asaju\Desktop\develop_test\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\build_meta.py", line 421, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 48, in <module>
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\command\bdist_wheel.py", line 384, in run
          self.run_command("build")
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\dist.py", line 950, in run_command
          super().run_command(command)
        File "C:\Users\asaju\AppData\Local\Temp\pip-build-env-8cubcxnb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 40, in run
        File "C:\Python311\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['python', 'bundle_build.py']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for taipy
Failed to build taipy
ERROR: Could not build wheels for taipy, which is required to install pyproject.toml-based projects
```

### Runtime Environment

Windows 11, Python 3.11.5

### OS

Windows

### Version of Taipy

develop

### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
Interesting, it looks like the same issue we're seeing on Mac
where [max-old-space-size](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes) is supposed to bring fix when set to 8GB

https://sebhastian.com/javascript-heap-out-of-memory/

What's your node.js version ?

**Comment by AlexandreSajus** [comment]
Node.js v20.9.0

**Comment by AlexandreSajus** [comment]
Fixed in develop!
