### ISSUE TITLE
[🐛 BUG] Getting OS Error while using the GUI module.

### ISSUE THREAD

**Issue by RandomArnab** [Avaiga/taipy#1779]
### What went wrong? 🤔

Can't use the GUI module properly from an interactive Python prompt.
![image](https://github.com/user-attachments/assets/d5199436-06e2-42c8-8020-5dd9e911bd57)

=>
```
 File "C:\Users\arnaa\AppData\Local\Programs\Python\Python312\Lib\inspect.py", line 1096, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

### Proposed 'solution' (well it's not, really)

Taipy GUI cannot function properly in these conditions because it relies heavily on an actual Python source file, such as one available when running a script or from a Notebook session. Currently, there is no feasible workaround for this limitation.

To address this, we should document the limitation clearly and implement an error message that accurately explains the issue, replacing the existing cryptic exception message.

### Acceptance Criteria

- [ ] Ensure the new code is unit tested, and check that the code coverage is at least 90%.
- [ ] Create related issues in taipy-doc for documentation and Release Notes.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [X] I am willing to work on this issue (optional)

**Comment by FlorianJacta** [comment]
What Taipy version are you using? Do you use any tools that can conflict with Taipy?

**Comment by RandomArnab** [comment]
Taipy version is 3.1.1. I've tried it on multiple environments with python versions of 3.11 and 3.12 but got the same os error while calling the GUI module.

**Comment by FlorianJacta** [comment]
Thank you for the quick answer! Are you coding in a cloud environment? 

Can you test:

```python
from taipy.gui import Gui 

Gui(page="# Hello world").run()
```

**Comment by RandomArnab** [comment]
No, I'm running locally. 
Still the same error however.
![image](https://github.com/user-attachments/assets/f0ee3ee7-eb3a-46b7-9653-d99f1e94cab2)

**Comment by FlorianJacta** [comment]
Did you create a brand new environment for your Taipy installation? Maybe, that could fix this issue.

@FabienLelaquais @FredLL-Avaiga Do you have any idea?

**Comment by RandomArnab** [comment]
I tried both ways, on my pre-existing environment with 3.11 python version and on a new environment with 3.12.

**Comment by FredLL-Avaiga** [comment]
if think the problem is that you're trying in the console and we need a file...

**Comment by FredLL-Avaiga** [comment]
I guess we should give a proper error message

**Comment by FlorianJacta** [comment]
True, I can replicate the issue:

```python
>>> from taipy.gui import Gui
>>> Gui("Hello").run()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jacta\.conda\envs\4.0\Lib\site-packages\taipy\gui\gui.py", line 2705, in run
    self.__var_dir.set_default(self.__frame)
  File "C:\Users\jacta\.conda\envs\4.0\Lib\site-packages\taipy\gui\utils\_variable_directory.py", line 31, in set_default
    self.add_frame(frame)
  File "C:\Users\jacta\.conda\envs\4.0\Lib\site-packages\taipy\gui\utils\_variable_directory.py", line 38, in add_frame
    imported_var_list = _get_imported_var(frame)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacta\.conda\envs\4.0\Lib\site-packages\taipy\gui\utils\get_imported_var.py", line 21, in _get_imported_var
    st = ast.parse(inspect.getsource(frame))
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacta\.conda\envs\4.0\Lib\inspect.py", line 1279, in getsource
    lines, lnum = getsourcelines(object)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacta\.conda\envs\4.0\Lib\inspect.py", line 1261, in getsourcelines
    lines, lnum = findsource(object)
                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacta\.conda\envs\4.0\Lib\inspect.py", line 1090, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

You should use Python files to run a Taipy application.

**Comment by Paulie-Aditya** [comment]
using python files should solve the issue. As far as I understood the issue is occurring due to the code being run on a python console

**Comment by SGCODEX** [comment]
@jrobinAV @Dr-Irv 
Hi, please assign me this issue under Devfest ai and Hacktoberfest

**Comment by FlorianJacta** [comment]
It seems that you are already assigned to another issue @SGCODEX

**Comment by aniketh-varma** [comment]
Hi @FlorianJacta, I can work on this issue. It would be great if you could explain the steps required to solve the issue/preferred solution since this will be my first PR for this repo.

**Comment by jrobinAV** [comment]
@aniketh-varma Let me assign the issue to you. Thanks for your help. 

For your questions, I let @FabienLelaquais @FredLL-Avaiga @dinhlongviolin1 @namnguyen20999 answer. They are the right persons.

**Comment by aniketh-varma** [comment]
Hey @FabienLelaquais @FredLL-Avaiga @dinhlongviolin1 @namnguyen20999 , can you please help me with a preferred solution for the issue.

**Comment by FabienLelaquais** [comment]
Hi @RandomArnab, @aniketh-varma, and @SGCODEX.
Thank you for your interest in the topic.

Unfortunately (or fortunately), @Paulie-Aditya is right (and @FlorianJacta confirms it): Taipy GUI cannot run straight from the console because it needs runtime information (like locating callback functions or tricky bindings) that are available only when the script is an actual file.
Interactive Python interpreters do not provide such a facility, and we fail to do anything.

As @FredLL-Avaiga points out, the least Taipy could do is document this limitation and issue a more informative error message.
We will, in the short term.

I recommend we keep this issue open, and I add a note on this discovery in the description.

Thanks again,

**Comment by JosuaCarl** [comment]
Just to add here for future travelers: This also makes building an application into a binary (for example with `pyinstaller`) hard (or impossible, still trying to figure that out), because the original files are not preserved in their pythonic form. 
If anyone knows of an easy way to distribute a taipy app, I would be very keen on knowing.

**Comment by janhavi-sys** [comment]
i would try to solve this issue  please assign me this issue
