### ISSUE TITLE
Cannot use lambda parameters in Page Builder API elements

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy#1816]
### What went wrong? 🤔

Run the code below.
The terminal will show that the lambda parameters cannot be bound.

Now replacing the page with the Markdown equivalent:
```
page = Markdown(
    "<|{data}|table|style={lambda _, row: 'blue-row' if row % 2 else 'red-row'}|show_all|>",
    style={
        ".blue-row>td": {"color": "white", "background-color": "blue"},
        ".red-row>td": {"color": "yellow", "background-color": "red"},
    },
)
```
everything works properly.

### Expected Behavior

tgb or Markdown should behave similarly. Meaning: the lambda works.

### Steps to Reproduce Issue

```
import taipy.gui.builder as tgb
from taipy.gui import Gui

x_range = range(-10, 11, 4)
data = {"x": x_range, "y": [x * x for x in x_range]}

with tgb.Page(
    style={
        ".blue-row>td": {"color": "white", "background-color": "blue"},
        ".red-row>td": {"color": "yellow", "background-color": "red"},
    }
) as page:
    tgb.table("{data}", style=lambda s, row: 'blue-row' if row % 2 else 'red-row', show_all=True)

Gui(page=page).run(stylekit=False)
```

### Workaround

Set the lambda function as an expression in a string:
```
tgb.table("{data}", style="{lambda s, row: 'blue-row' if row % 3 else 'red-row'}", show_all=True)
```

### Version of Taipy

develop

### Additional Context

Trace in terminal:

```bash
--- 4 warning(s) were found for page '/'  ---
 - Warning 1: Variable 's' is not available in either the '__main__' or '__main__' modules.
 - Warning 2: Variable 's' is not defined (in expression '{__lambda_5531718c857b4d30be287c5a1105ad15(s, row)}'):
Traceback (most recent call last):
  File "...\taipy\gui\utils\_evaluator.py", line 122, in _analyze_expression
    var_val[var_name] = _getscopeattr_drill(gui, encoded_var_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\taipy\gui\utils\_attributes.py", line 26, in _getscopeattr_drill
    return attrgetter(name)(gui._get_data_scope())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 's'

 - Warning 3: Variable 'row' is not available in either the '__main__' or '__main__' modules.
 - Warning 4: Variable 'row' is not defined (in expression '{__lambda_5531718c857b4d30be287c5a1105ad15(s, row)}'):
Traceback (most recent call last):
  File "...\taipy\gui\utils\_evaluator.py", line 122, in _analyze_expression
    var_val[var_name] = _getscopeattr_drill(gui, encoded_var_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....\taipy\gui\utils\_attributes.py", line 26, in _getscopeattr_drill
    return attrgetter(name)(gui._get_data_scope())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'types.SimpleNamespace' object has no attribute 'row'

----------------------------------------------

```
```


### Acceptance Criteria

- [ ] Ensure new code is unit tested, and check code coverage is at least 90%.
- [ ] Create related issue in taipy-doc for documentation and Release Notes.


### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by FredLL-Avaiga** [comment]
the style property here should be bound to a callback but the parsing doesn't know about it
