### ISSUE TITLE
[🐛 BUG] Imported page scope issue with AuthorizedPage

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#2176]
### What went wrong? 🤔

Local variable is not found in an AuthorizedPage imported from another module.

Example code, zip file attached below:

```
.
├── main.py
└── pages/
    ├── admin.py
    ├── home.py
    └── forbidden.py
```

main.py:
```py
import taipy as tp
import taipy.gui.builder as tgb
from taipy import Config
from taipy.auth import AnyOf
from taipy.enterprise.gui import AuthorizedPage
from taipy.gui import Gui

from pages.admin import admin_page
from pages.home import home_page
from pages.forbidden import forbidden_page

Config.configure_authentication(
    protocol="taipy",
    roles={"bob": ["TAIPY_ADMIN"]},
)


with tgb.Page() as root_page:
    tgb.navbar()


pages = {
    "/": root_page,
    "home": home_page,
    "admin": AuthorizedPage(AnyOf(["TAIPY_ADMIN"], admin_page, forbidden_page)),
}


def on_init(state):
    tp.enterprise.gui.login(state, "bob", "bob")


if __name__ == "__main__":
    gui = Gui(pages=pages)
    gui.run()
```

admin.py:
```py
import taipy.gui.builder as tgb

with tgb.Page() as admin_page:
    text = "Admin page"
    tgb.text("{text}")
```

home.py and forbidden.py:
```py
# Same as admin.py, but with the respective module names.
```

home.py has the expected behaviour where the `text` local variable is properly displayed. However, admin.py and forbidden.py do not display the text, and print the following error:

```
WARNING:root:
--- 2 warning(s) were found for page 'admin'  ---
 - Warning 1: Variable 'text' is not available in either the '__main__' or '__main__' modules.
 - Warning 2: Variable 'text' is not defined (in expression '{text}'):
Traceback (most recent call last):
  File "/home/enterprise/lib/python3.10/site-packages/taipy/gui/utils/_evaluator.py", line 131, in _analyze_expression
    var_val[var_name] = _getscopeattr_drill(gui, encoded_var_name)
  File "/home/enterprise/lib/python3.10/site-packages/taipy/gui/utils/_attributes.py", line 26, in _getscopeattr_drill
    return attrgetter(name)(gui._get_data_scope())
AttributeError: 'types.SimpleNamespace' object has no attribute 'text'
```

### Expected Behavior

AuthorizedPage should have the scope of the rendered page (i.e. forbidden.py or admin.py), depending on the Credentials.

### Steps to Reproduce Issue

Contains example code above:
[AuthorizedPage_local_module_scoping.zip](https://github.com/user-attachments/files/17544204/AuthorizedPage_local_module_scoping.zip)

1. Run main.py
2. Navigate to admin page and observe
  a. "Admin page" text is not displayed on screen
  b. Error is printed in console

### Solution Proposed

NA

### Screenshots

NA

### Browsers

Chrome

### OS

Windows, Linux

### Version of Taipy

taipy-enterprise==4.0.0

### Acceptance Criteria

- [ ] A unit test reproducing the bug is added.
- [ ] Any new code is covered by a unit tested.
- [ ] Check code coverage is at least 90%.
- [ ] The bug reporter validated the fix.
- [ ] Related issue(s) in taipy-doc are created for documentation and Release Notes are updated.

### Code of Conduct

- [X] I have checked the [existing issues](https://github.com/Avaiga/taipy/issues?q=is%3Aissue+).
- [ ] I am willing to work on this issue (optional)

**Comment by trgiangdo** [comment]
I believe this issue belongs to the `taipy-enterprise` repo.

Should we move the issue there?

**Comment by arcanaxion** [comment]
@trgiangdo I don't think I'll be able to view the issue there so do message me if you guys can't reproduce it
