### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by keell0renz** [Avaiga/taipy#255]
Hello! I have problems with installation, tried to reinstall alembic and sqlalchemy, same problem.

`
❯ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from taipy import Gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sidi0us/.local/lib/python3.9/site-packages/taipy/__init__.py", line 25, in <module>
    from taipy.rest._init import *  # type: ignore
  File "/home/sidi0us/.local/lib/python3.9/site-packages/taipy/rest/__init__.py", line 23, in <module>
    from ._init import *
  File "/home/sidi0us/.local/lib/python3.9/site-packages/taipy/rest/_init.py", line 12, in <module>
    from .rest import Rest
  File "/home/sidi0us/.local/lib/python3.9/site-packages/taipy/rest/rest.py", line 13, in <module>
    from .app import create_app as _create_app
  File "/home/sidi0us/.local/lib/python3.9/site-packages/taipy/rest/app.py", line 16, in <module>
    from . import api
  File "/home/sidi0us/.local/lib/python3.9/site-packages/taipy/rest/api/__init__.py", line 12, in <module>
    from . import error_handler, views
  File "/home/sidi0us/.local/lib/python3.9/site-packages/taipy/rest/api/error_handler.py", line 29, in <module>
    from .views import blueprint
File "/home/sidi0us/.local/lib/python3.9/site-packages/taipy/rest/api/views.py", line 18, in <module>
    from ..extensions import apispec
  File "/home/sidi0us/.local/lib/python3.9/site-packages/taipy/rest/extensions.py", line 18, in <module>
    from flask_migrate import Migrate
  File "/home/sidi0us/.local/lib/python3.9/site-packages/flask_migrate/__init__.py", line 7, in <module>
    from alembic import __version__ as __alembic_version__
  File "/usr/lib/python3/dist-packages/alembic/__init__.py", line 3, in <module>
    from . import context  # noqa
  File "/usr/lib/python3/dist-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/usr/lib/python3/dist-packages/alembic/runtime/environment.py", line 1, in <module>
    from .migration import MigrationContext
  File "/usr/lib/python3/dist-packages/alembic/runtime/migration.py", line 15, in <module>
    from .. import ddl
  File "/usr/lib/python3/dist-packages/alembic/ddl/__init__.py", line 1, in <module>
    from . import mssql  # noqa
  File "/usr/lib/python3/dist-packages/alembic/ddl/mssql.py", line 8, in <module>
    from .base import AddColumn
  File "/usr/lib/python3/dist-packages/alembic/ddl/base.py", line 11, in <module>
    from ..util import sqla_compat
  File "/usr/lib/python3/dist-packages/alembic/util/__init__.py", line 26, in <module>
    from .sqla_compat import has_computed  # noqa
  File "/usr/lib/python3/dist-packages/alembic/util/sqla_compat.py", line 13, in <module>
    from sqlalchemy.sql.expression import _BindParamClause
ImportError: cannot import name '_BindParamClause' from 'sqlalchemy.sql.expression' (/home/sidi0us/.local/lib/python3.9/site-packages/sqlalchemy/sql/expression.py)
`

**Comment by keell0renz** [comment]
Fixed, thanks!

**Comment by cse0001** [comment]
The root cause with your issue stems from a dependency management conflict between two software ecosystems. According to the error message, your 'sqlalchemy' was installed using 'pip' at the path `/home/sidi0us/.local/lib/python3.9/site-packages/sqlalchemy`. The 'alembic' that depends on it was installed using 'apt' at the path `/usr/lib/python3/dist-packages/alembic`. The versions of the two are not compatible. In fact, there is a version of 'sqlalchemy' in the system that 'alembic' correctly depends on, but the Python interpreter prioritizes the 'sqlalchemy' installed by 'pip', leading to this issue. There are typically two solutions to this problem: (1) Use 'pip' to uninstall sqlalchemy, and then reinstall it using 'apt', or uninstall 'alembic' using 'apt' and reinstall it using 'pip'. (2) Use Python's imp module to customize the path and import the 'sqlalchemy' from the 'apt' path before importing 'flask'. An example is as follows:

    import imp
    path = ['/usr/lib/python3/dist-packages']
    fp, pathname, description = imp.find_module('sqlalchemy', path)
    imp.load_module("sqlalchemy", fp, pathname, description)

Hope my diagnosis is helpful to you！ @keell0renz
