### ISSUE TITLE
BUG-Partials and page scope give errors

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy#561]
**Description**

There is a problem when using a partial inside a page. The partial inside the page is in "global scope" while the elements that we want to display can be of the page scope.

**How to reproduce**

app.py
```python
from taipy.gui import Gui
from test import test_md

pages_app = {
    "/": "<|navbar|>",
    "test": test_md,
}


md_for_chart = "<|{data}|chart|rebuild|mode=markers|x=x|y=y|marker={marker}|>"

gui = Gui(pages=pages_app)
partial_for_chart = gui.add_partial(md_for_chart)
gui.run()
```

test.py
```python
from taipy.gui import Gui, Markdown
import pandas as pd

all_data = pd.DataFrame({
    "x" : [1, 2, 3, 4],
    "y" : [1, 2, 3, 4],
    "category": ["dog", "cat", "cat", "dog"],
    "bubble_size": [10, 50, 50, 10],
    "color": ["red", "green", "green", "red"]
})

categories = list(all_data["category"].unique())
selected_category = "dog"
data = all_data[all_data["category"] == selected_category]

marker = {
    "color": "color",
    "size": "bubble_size"
}

def on_change_cat(state):
    state.data = all_data[all_data["category"] == state.selected_category]
    state.partial_for_chart.update_content(state, md_for_chart)

test_md = Markdown("""
<|{selected_category}|selector|lov={categories}|dropdown|label=Category|on_change=on_change_cat|>
<|part|partial={partial_for_chart}|>
""")

#md_for_chart = "<|{data}|chart|rebuild|mode=markers|x=x|y=y|marker={marker}|>"
```

This raises an error because data and marker are not accesible.

**Expected behavior**
Partials should have the scope of the page.

**Runtime environment**
Taipy 2.4

**Comment by FlorianJacta** [comment]
If I try to `from test import *`, the callback will not update the chart like it should. If I don't put the Markdown object, everything works fine again. There is a page scope issue.

**Comment by FlorianJacta** [comment]
From @arcanaxion (https://github.com/Avaiga/taipy/issues/595):

# Description
Updating a partial's contents with a variable name defined in the same submodule as the partial raises an error.

# Example

This example should allow the user to select multiple ticker names to plot multiple traces on a line chart.

```python
# subpage.py
from taipy.gui import Markdown
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/stockdata.csv")

stock_list = df.columns[:-1].to_list()
selected_stocks = stock_list[:2]

def create_partial_str(selected_stocks):
    y_params = "|".join([f"y[{i+1}]={ticker}" for i, ticker in enumerate(selected_stocks)])
    return f"<|{{df}}|chart|x=Date|{y_params}|>"

initial_df_partial = Markdown(create_partial_str(selected_stocks))
subpage_md = Markdown(
"""
<|{selected_stocks}|selector|lov={stock_list}|multiple|on_change=update_df_partial|>

<|part|partial={df_partial}|>
""")

def update_df_partial(state):
    state.df_partial.update_content(state, create_partial_str(state.selected_stocks))
```

```python
# main.py
from taipy.gui import Gui, Markdown
from subpage import subpage_md, initial_df_partial


root_md = Markdown("<|navbar|>")

pages = {
    "/": root_md,
    "subpage": subpage_md,
}

gui = Gui(pages=pages)
df_partial = gui.add_partial(initial_df_partial)
gui.run()
```

The webpage initially loads with the 2 preselected tickers. Attempting to further (un)select tickers displays "something went wrong" in red on the page and causes the following warning in the terminal:

```
--- 8 warning(s) were found for page 'TaiPy_partials_0'  ---
 - Warning 1: Variable 'df' is not available in either the '__main__' or '__main__' modules.
 - Warning 2: Variable 'df' is not defined (in expression '{df}'):
Traceback (most recent call last):
  File "/home/.../.venv/lib/python3.10/site-packages/taipy/gui/utils/_evaluator.py", line 106, in _analyze_expression
    var_val[var_name] = _getscopeattr_drill(gui, encoded_var_name)
  File "/home/.../.venv/lib/python3.10/site-packages/taipy/gui/utils/_attributes.py", line 26, in _getscopeattr_drill
    return attrgetter(name)(gui._get_data_scope())
AttributeError: 'types.SimpleNamespace' object has no attribute 'df'
```

I hope this is a bug or I am doing something wrong because I'd rather not import df into the main module.

**Comment by AlexandreSajus** [comment]
Is this fixed? If not, can you provide a minimal reproducible example?

**Comment by arcanaxion** [comment]
> Is this fixed?

Just tested it on develop -- I can still reproduce the issue.

> If not, can you provide a minimal reproducible example?

Are the present examples too long?

**Comment by FredLL-Avaiga** [comment]
The issue here is that when updating the partial the information on the current context is lost.
We can retrieve the context from the old content.
If one wants to set a new context for the new content, he would have to set it explicitly (as done before)
