### ISSUE TITLE
Scope issue when updating partial defined in submodule

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy#595]
# Description
Updating a partial's contents with a variable name defined in the same submodule as the partial raises an error.

# Example

This example should allow the user to select multiple ticker names to plot multiple traces on a line chart.

```python
# subpage.py
from taipy.gui import Markdown
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/stockdata.csv")

stock_list = df.columns[:-1].to_list()
selected_stocks = stock_list[:2]

def create_partial_str(selected_stocks):
    y_params = "|".join([f"y[{i+1}]={ticker}" for i, ticker in enumerate(selected_stocks)])
    return f"<|{{df}}|chart|x=Date|{y_params}|>"

initial_df_partial = Markdown(create_partial_str(selected_stocks))
subpage_md = Markdown(
"""
<|{selected_stocks}|selector|lov={stock_list}|multiple|on_change=update_df_partial|>

<|part|partial={df_partial}|>
""")

def update_df_partial(state):
    state.df_partial.update_content(state, create_partial_str(state.selected_stocks))
```

```python
# main.py
from taipy.gui import Gui, Markdown
from subpage import subpage_md, initial_df_partial


root_md = Markdown("<|navbar|>")

pages = {
    "/": root_md,
    "subpage": subpage_md,
}

gui = Gui(pages=pages)
df_partial = gui.add_partial(initial_df_partial)
gui.run()
```

The webpage initially loads with the 2 preselected tickers. Attempting to further (un)select tickers displays "something went wrong" in red on the page and causes the following warning in the terminal:

```
--- 8 warning(s) were found for page 'TaiPy_partials_0'  ---
 - Warning 1: Variable 'df' is not available in either the '__main__' or '__main__' modules.
 - Warning 2: Variable 'df' is not defined (in expression '{df}'):
Traceback (most recent call last):
  File "/home/.../.venv/lib/python3.10/site-packages/taipy/gui/utils/_evaluator.py", line 106, in _analyze_expression
    var_val[var_name] = _getscopeattr_drill(gui, encoded_var_name)
  File "/home/.../.venv/lib/python3.10/site-packages/taipy/gui/utils/_attributes.py", line 26, in _getscopeattr_drill
    return attrgetter(name)(gui._get_data_scope())
AttributeError: 'types.SimpleNamespace' object has no attribute 'df'
```

I hope this is a bug or I am doing something wrong because I'd rather not import df into the main module.

**Comment by FlorianJacta** [comment]
This may be related to https://github.com/Avaiga/taipy/issues/561

**Comment by arcanaxion** [comment]
Yes, I think you're right. Sorry I missed that!

**Comment by FlorianJacta** [comment]
I am not sure about it, however.
